//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSCADAWebApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarmsetting
    {
        public int Id { get; set; }
        public string TagName { get; set; }
        public string TagAlias { get; set; }
        public string ValueStatus1 { get; set; }
        public string ValueStatus2 { get; set; }
        public string ValueStatus3 { get; set; }
        public string ValueStatus4 { get; set; }
        public string ValueStatus5 { get; set; }
        public string Email { get; set; }
        public string SMS { get; set; }
    }
}
